[build-system]
# build-backend = "hatchling.build"
# requires = ["hatchling", "hatch-vcs"]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dmg"
description = "Differentiable modeling framework on PyTorch"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Leo Lonzarich", email = "lglonzaric@gmail.com"},
    {name = "Tadd Bindas", email = "taddbindas@gmail.com"},
    {name = "Farshid Rahmani"},
    {name = "Yalan Song", email = "songyalan1@gmail.com"},
]
maintainers = [
    {name = "Leo Lonzarich", email = "lglonzaric@gmail.com"},
    {name = "Tadd Bindas", email = "taddbindas@gmail.com"},
    {name = "Yalan Song", email = "songyalan1@gmail.com"},
    {name = "Chaopeng Shen", email = "shen.chaopeng@gmail.com"}, 
    {name = "Doaa Aboelyazeed", email = "doaa.barawy@gmail.com"},
    {name = "Kathryn Lawson", email = "kel33@psu.edu"},
]
requires-python = ">=3.9.0"
dynamic = ["version"]
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.21.0",
    "scipy>=1.7.0",
    "pydantic>=1.8.0",
    "pandas>=1.3.0",
    "omegaconf>=2.1.0",
    "tqdm>=4.61.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache 2.0 License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://mhpi.github.io/codes/frameworks/"
Repository = "https://github.com/mhpi/generic_deltaModel"

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=5.0.0",
]
dev = [
    # "black",
    # "flake8",
    # "mypy",
    "isort>=5.0.0",
]

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "dmg/src/dmg/_version.py"

# [tool.black]
# line-length = 88
# target-version = ["py312"]
# include = '\.pyi?$'
# exclude = '''
# /(
#     \.git
#   | \.vscode
#   | \.mypy_cache
#   | \.venv
#   | \archive
# )/
# '''
# skip-string-normalization = true

# [tool.flake8]
# max-line-length = 88
# extend-ignore = ["E203", "W503"]
# per-file-ignores = [
#     "__init__.py:F401",
#     "tests/*:D100,D101,D102,D103",
# ]
# exclude = [
#     ".git",
#     ".vscode",
#     "mypy_cache",
#     ".venv",
#     "archive",
# ]

[tool.mypy]
python_version = "3.12"
strict = true

[tool.isort]
profile = "black"

[tool.uv.sources]
torch = [
    { index = "pytorch-cu121", marker = "platform_system != 'Darwin'"},
]
torchvision = [
    { index = "pytorch-cu121", marker = "platform_system != 'Darwin'"},
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
