[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]
# requires = ["setuptools>=42", "wheel"]
# build-backend = "setuptools.build_meta"

[project]
name = "dMG"
description = "Differentiable modeling framework on PyTorch"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Leo Lonzarich", email = "lglonzaric@gmail.com"},
    {name = "Tadd Bindas", email = "taddbindas@gmail.com"},
    {name = "Farshid Rahmani"},
    {name = "Yalan Song", email = "songyalan1@gmail.com"},
]
maintainers = [
    {name = "Leo Lonzarich", email = "lglonzaric@gmail.com"},
    {name = "Tadd Bindas", email = "taddbindas@gmail.com"},
    {name = "Yalan Song", email = "songyalan1@gmail.com"},
    {name = "Chaopeng Shen", email = "shen.chaopeng@gmail.com"}, 
    {name = "Doaa Aboelyazeed", email = "doaa.barawy@gmail.com"},
    {name = "Kathryn Lawson", email = "kel33@psu.edu"},
]
requires-python = ">=3.9.0"
dynamic = ["version"]
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.21.0",
    "scipy>=1.7.0",
    "pydantic>=1.8.0",
    "pandas>=1.3.0",
    "omegaconf>=2.1.0",
    "tqdm>=4.61.0",
    "matplotlib>=3.4.0",
    "scikit-learn>=0.24.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache 2.0 License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://mhpi.github.io/codes/frameworks/"
Repository = "https://github.com/mhpi/generic_deltaModel"

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=5.0.0",
]
dev = [
    # "mypy",
    "isort>=5.0.0",
    "ruffus>=2.8.0",
]

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/dMG/_version.py"

[tool.hatch.metadata]
allow-direct-references = true

# [project.optional-dependencies]
# cpu = [
#     "torch==2.6.0",
#     "torchvision==0.21.0",
# ]
# cu124 = [
#     "torch==2.6.0",
#     "torchvision==0.21.0",
#     "cupy-cuda12x==13.4.0",
# ]

# [tool.black]
# line-length = 88
# target-version = ["py312"]
# include = '\.pyi?$'
# exclude = '''
# /(
#     \.git
#   | \.vscode
#   | \.mypy_cache
#   | \.venv
#   | \archive
# )/
# '''
# skip-string-normalization = true

# [tool.flake8]
# max-line-length = 88
# extend-ignore = ["E203", "W503"]
# per-file-ignores = [
#     "__init__.py:F401",
#     "tests/*:D100,D101,D102,D103",
# ]
# exclude = [
#     ".git",
#     ".vscode",
#     "mypy_cache",
#     ".venv",
#     "archive",
# ]

[tool.mypy]
python_version = "3.12"
strict = true

[tool.isort]
profile = "black"

[tool.uv.sources]
torch = [
    { index = "pytorch-cu121", marker = "platform_system != 'Darwin'"},
]
torchvision = [
    { index = "pytorch-cu121", marker = "platform_system != 'Darwin'"},
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.pytest.ini_options]
testpaths = ["tests"]
xfail_strict = true

addopts = [
    "--import-mode=importlib",  # allow using test files with same name
]

[tool.ruff]
src = ["src"]
line-length = 88
lint.select = [
    "F",  # Errors detected by Pyflakes
    "E",  # Error detected by Pycodestyle
    "W",  # Warning detected by Pycodestyle
    "I",  # isort
    "D",  # pydocstyle
    "B",  # flake8-bugbear
    "TID",  # flake8-tidy-imports
    "C4",  # flake8-comprehensions
    "BLE",  # flake8-blind-except
    "UP",  # pyupgrade
    "RUF100",  # Report unused noqa directives
]
exclude = [
    ".git",
    ".vscode",
    "archive",
    "dev",
]
lint.ignore = [
    # line too long -> we accept long comment lines; black gets rid of long code lines
    "E501",
    # Do not assign a lambda expression, use a def -> lambda expression assignments are convenient
    "E731",
    # allow I, O, l as variable names -> I is the identity matrix
    "E741",
    # Missing docstring in public package
    "D104",
    # Missing docstring in public module
    "D100",
    # Missing docstring in __init__
    "D107",
    # Errors from function calls in argument defaults. These are fine when the result is immutable.
    "B008",
    # __magic__ methods are are often self-explanatory, allow missing docstrings
    "D105",
    # first line should end with a period [Bug: doesn't work with single-line docstrings]
    "D400",
    # First line should be in imperative mood; try rephrasing
    "D401",
    ## Disable one in each pair of mutually incompatible rules
    # We don't want a blank line before a class docstring
    "D203",
    # We want docstrings to start immediately after the opening triple quote
    "D213",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"docs/*" = ["I"]
"tests/*" = ["D"]
"*/__init__.py" = ["F401"]
