# This configuration file is specifically for the multi-scale, differentiable, hydrologic model dHBV 1.1p from Song et al., 2024. If you find this code is useful to your work, please cite this paper below:
# Yalan Song, Kamlesh Sawadekar, Jonathan Frame, et al. Improving physics-informed, differentiable hydrologic models for capturing unseen extreme events. ESS Open Archive. 7 August 2024. https://doi.org/10.22541/essoar.172304428.82707157/v1.

defaults:
    - _self_
    - hydra: settings
    - observations: camels_531 # camels_531, camels_671 


## General -------------------------------#
mode: train_test  # train, test, train_test
random_seed: 111111
device: cuda
gpu_id: 0

data_loader: loader_hydro
data_sampler: sampler_hydro
trainer: trainer

save_path: ../results
trained_model: path/to/trained/model/ ### TODO: add here model file here


## Training ------------------------------#
train:
    start_time: 1999/10/01
    end_time: 2008/09/30
    target: [flow_sim]
    optimizer: Adadelta
    batch_size: 100
    epochs: 100
    start_epoch: 0
    save_epoch: 5


## Testing -------------------------------#
test:
    start_time: 1989/10/01
    end_time: 1999/09/30
    batch_size: 25
    test_epoch: 100
    evaluation: False


## Loss Function -------------------------#
loss_function:
    model: NseLossBatch


## dPL Model -----------------------------#
dpl_model:
    rho: 365
    
    phy_model:
        ## Citations ##
        # HBV 1.1p (HBV_1_1p): Song, Y., Sawadekar, K., Frame, J. M., Pan, M., Clark, M., Knoben, W. J. M., Wood, A. W., Patel, T., & Shen, C. (2024b). Improving physics-informed, differentiable hydrologic models for capturing unseen extreme events. ESS Open Archive. https://doi.org/10.22541/essoar.172304428.82707157/v1.

        model: [HBV_1_1p]
        nmul: 16
        warm_up: 365
        warm_up_states: False
        dy_drop: 0.0
        dynamic_params:
            HBV_1_1p: [parBETA, parK0, parBETAET]

        routing: True
        use_log_norm: []
        nearzero: 1e-5

        forcings: [
            prcp,
            tmean,
            pet,
        ]
        attributes: []

    nn_model:
        model: LSTM
        dropout: 0.5
        hidden_size: 256
        learning_rate: 1.0
        lr_scheduler: None
        lr_scheduler_params:
            step_size: 10
            gamma: 0.5
        
        forcings: [
            prcp,
            tmean,
            pet,
        ]
        attributes: [
            p_mean,
            pet_mean,
            p_seasonality,
            frac_snow,
            aridity,
            high_prec_freq,
            high_prec_dur,
            low_prec_freq,
            low_prec_dur,
            elev_mean,
            slope_mean,
            area_gages2,
            frac_forest,
            lai_max,
            lai_diff,
            gvf_max,
            gvf_diff,
            dom_land_cover_frac,
            dom_land_cover,
            root_depth_50,
            soil_depth_pelletier,
            soil_depth_statsgo,
            soil_porosity,
            soil_conductivity,
            max_water_content,
            sand_frac,
            silt_frac,
            clay_frac,
            geol_1st_class,
            glim_1st_class_frac,
            geol_2nd_class,
            glim_2nd_class_frac,
            carbonate_rocks_frac,
            geol_porosity,
            geol_permeability,
        ]
