defaults:
    - _self_
    - hydra: settings
    - observations: MERIT_forward_zone


## General -------------------------------#
mode: test  # train, test, train_test
ensemble_type: none
random_seed: 111111
device: cuda
gpu_id: 0

save_path: ../results
trained_model: /projects/mhpi/yxs275/model/generic_deltaModel_dhbv2.0/savedModel/HBV2.0/



## Training ------------------------------#
train:
    start_time: 2000/01/01
    end_time: 2000/12/31
    target: [y_var]
    optimizer: Adadelta
    batch_size: 100
    epochs: 50
    start_epoch: 0
    save_epoch: 5


## Testing -------------------------------#
test:
    start_time: 1980/01/01
    end_time: 2020/12/31
    batch_size: 400
    test_epoch: 100
    evaluation: False


## Loss Function -------------------------#
loss_function:
    model: RmseLossComb
    

## dPL Model -----------------------------#
dpl_model:
    nmul: 4
    rho: 365
    
    phy_model:
        #HBV : Feng, Dapeng, Jiangtao Liu, Kathryn Lawson, and Chaopeng Shen."Differentiable, Learnable, Regionalized Process‐Based Models With Multiphysical Outputs can Approach State‐Of‐The‐Art Hydrologic Prediction Accuracy." Water Resources Research 58, no. 10 (2022): e2022WR032404.
        #HBV_1_1p (1.1p) : Song, Y., Sawadekar, K., Frame, J. M., Pan, M., Clark, M., Knoben, W. J. M., Wood, A. W., Patel, T., & Shen, C. (2024b). Improving physics-informed, differentiable hydrologic models for capturing unseen extreme events. ESS Open Archive. https://doi.org/10.22541/essoar.172304428.82707157/v1
        #HBV_adj: Song, Y., Knoben, W. J. M., Clark, M. P., Feng, D., Lawson, K., Sawadekar, K., & Shen, C. (2024a). When ancient numerical demons meet physics-informed machine learning: Adjoint-based gradients for implicit differentiable modeling. Hydrology and Earth System Sciences, 28(13), 3051–3077. https://doi.org/10.5194/hess-28-3051-2024
        model: [HBV_2_0]  # HBV, HBV_1_1p, HBV_adj
        warm_up: 0
        warm_up_states: True  # If False, tracking gradient from spin-up; Increase your computational time; Slightly improve accuracy; Not used by HBV_adj.
        dy_drop: 0.0
        dynamic_params:
            HBV: [parBETA, parBETAET]
            HBV_adj: [parBETA,parFC, parBETAET]
            HBV_1_1p: [parBETA, parBETAET, parK0]
            HBV_2_0: [parBETA, parK0, parBETAET]

        routing: True
        AD_efficient: True   ## Specific for HBV_adj
        use_log_norm: []
        nearzero: 1e-5

        forcings: [
            P,
            Temp,
            PET,
        ]

    nn_model:
        model: LSTMMLP

        LSTM_dropout: 0.5
        LSTM_hidden_size: 64
        MLP_dropout: 0.5
        MLP_hidden_size: 4096
        learning_rate: 1.0
        lr_scheduler: None
        lr_scheduler_params:
            step_size: 10
            gamma: 0.5
        
        forcings: [
            P,
            Temp,
            PET,
        ]
        attributes: [
            ETPOT_Hargr,
            FW,
            HWSD_clay,
            HWSD_gravel,
            HWSD_sand,
            HWSD_silt,
            NDVI,
            Porosity,
            SoilGrids1km_clay,
            SoilGrids1km_sand,
            SoilGrids1km_silt,
            T_clay,
            T_gravel,
            T_sand,
            T_silt,
            aridity,
            glaciers,
            meanP, 
            meanTa,
            meanelevation,
            meanslope,
            permafrost,
            permeability,
            seasonality_P,
            seasonality_PET, 
            now_fraction,
            snowfall_fraction,
            uparea,
        ]

